# Generated by Django 2.2.3 on 2020-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddressLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_data', models.CharField(max_length=255)),
                ('changed_table', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'address_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ssn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_data', models.CharField(max_length=255)),
                ('changed_table', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'customer_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('ssn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_data', models.CharField(max_length=255)),
                ('changed_table', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'delivery_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_data', models.CharField(max_length=255)),
                ('changed_table', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuFood',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu_food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuFoodLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_data', models.CharField(max_length=255)),
                ('changed_table', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'menu_food_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingFactor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'shopping_factor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingFactorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_data', models.CharField(max_length=255)),
                ('changed_table', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'shopping_factor_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_data', models.CharField(max_length=255)),
                ('changed_table', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'store_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_factor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFactorsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('price_per', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_factors_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFactorsItemsLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_data', models.CharField(max_length=255)),
                ('changed_table', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_factors_items_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFactorsLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_data', models.CharField(max_length=255)),
                ('changed_table', models.CharField(max_length=255)),
                ('changed_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_factors_log',
                'managed': False,
            },
        ),
    ]
